# Generated by Django 4.2.5 on 2023-10-22 13:50

from django.db import migrations, models
import django_countries.fields
import etc.file_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(upload_to=etc.file_uploader.category_logo_uploader),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=etc.file_uploader.company_image_uploader),
        ),
    ]
