# Generated by Django 4.2.5 on 2023-10-31 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import etc.file_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('linkedIn', models.URLField(help_text='please enter your linkedin-profile url')),
                ('github', models.URLField(blank=True, help_text='please enter your github url', null=True)),
                ('cv', models.FileField(help_text='please upload your CV', upload_to=etc.file_uploader.job_apply_cv_uploader)),
                ('cover_litter', models.TextField(help_text='please enter your bio about yourself', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.job')),
            ],
        ),
    ]
