# Generated by Django 4.2.5 on 2023-10-31 15:16

import django.core.validators
from django.db import migrations, models
import etc.file_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_options_jobapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='cv',
            field=models.FileField(help_text='please upload your CV', upload_to=etc.file_uploader.job_apply_cv_uploader, validators=[django.core.validators.RegexValidator(code='invalid_pdf', message='Only PDF files are allowed.', regex='^.*\\.pdf$')]),
        ),
    ]
